services:
  myportfolio_site:
    container_name: myportfolio_site
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql_site:
    container_name: mysql_site
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

  nginx_site:
    container_name: nginx_site
    image: jonasal/nginx-certbot
    restart: always
    environment:
      - CERTBOT_EMAIL=traeyoungpointgod@gmail.com
      - DEBUG=1
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - myportfolio_site

volumes:
  mydatabase:
  nginx_secrets:

