name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Python Virtual Environment
        run: python -m venv env

      - name: Install Dependencies
        run: env/bin/pip install -r requirements.txt

      - name: Run Tests
        run: ./run_test.sh
